---
blank_issues_enabled: true
contact_links:
  - name: Enterprise Support
    url: https://osism.tech/support
    about: We provide enterprise support. Further information can be found on the linked page.
